name: github action CI

on:
  pull_request:
    branches:
      - main
      - testnet
  push:
    branches:
      - main
      - testnet

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Test solidity contracts
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v3-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Lint check
        run: npm run lint
      - name: Compile contracts
        run: npm run compile
      - name: Test contracts
        run: npm run test